type: object
properties:
  id:
    type: integer
    description: Unique identifier.
  name:
    type: string
    description: Product name.
  code:
    type:
      - string
      - 'null'
    description: Product code.
  net_price:
    type:
      - number
      - 'null'
    description: 'Net sale price (used if use_gross_price is false, otherwise it''s competed automatically).'
  gross_price:
    type:
      - number
      - 'null'
    description: 'Gross sale price (used if use_gross_price is false, otherwise it''s competed automatically).'
  use_gross_price:
    type: boolean
    description: Determine which price to use for calculations.
  default_vat:
    $ref: ./VatType.yaml
  net_cost:
    type:
      - number
      - 'null'
    description: Net cost of the product (used for received documents).
  measure:
    type:
      - string
      - 'null'
    description: Unit of measure.
  description:
    type: string
    description: Product description.
  category:
    type: string
    description: Product category.
  notes:
    type:
      - string
      - 'null'
    description: Extra notes.
  in_stock:
    type: boolean
    description: Determine if the product is in stock.
  stock_initial:
    type: number
    description: Product initial stock.
  stock_current:
    type: number
    description: |-
      [Read Only]
      Product current stock.
    readOnly: true
  average_cost:
    type: number
    description: Product average cost.
  average_price:
    type: number
    description: Product average price.
  created_at:
    type: string
  updated_at:
    type: string
required:
  - name
